export const SCREEN_NAME = {
  ADDVOCA: "AddVoca",
  LOGIN: "Login",
  REGISTER: "Register",
  LEARN: "Learn",
  POST: "Post",
  TEST: "Test",
  CHART: "Chart",
  ITEM_VOCA: "ItemVoca",
  OPTION_VOCA: "OptionVoca",
  CONNECT_VOCA: "ConnectVoca",
  PROFILE: "Profile",
  EDIT: "Edit",
  WELCOME: "Welcome",
  EDIT_PROFILE: "EditProfile",
  DETAIL_POST: "DetailProfile",
  MATCH_ALPHABET: "MatchAlphabet",
  CHAT: "Chat",
  DETAIL_USER: "DetailUser",
};
